name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: summary
    attributes:
      label: summary
      description: Please describe the summary.
      placeholder: summary
    validations:
      required: true
  - type: textarea
    id: Perspective
    attributes:
      label: Perspective
      description: Please describe the perspective.
      placeholder: Perspective
    validations:
      required: true
  - type: textarea
    id: How to reproduce
    attributes:
      label: How to reproduce
      description: Please describe the reproduction procedure.
      placeholder: How to reproduce
    validations:
      required: false
  - type: textarea
    id: Why fix this issue
    attributes:
      label: Why fix this issue
      description: Please describe why solve the issue.
      placeholder: Why fix this issue
    validations:
      required: false
  - type: textarea
    id: Root issue
    attributes:
      label: Root issue
      description: Please describe the Root issue.
      placeholder: Root issue
    validations:
      required: false
  - type: textarea
    id: How to solve
    attributes:
      label: How to solve
      description: Please describe How to solve.
      placeholder: How to solve
    validations:
      required: false
